package com.singularis.eateria.util

object FoodQuotes {
    val quotes: List<String> = listOf(
        "One cannot think well, love well, sleep well, if one has not dined well. — Virginia Woolf",
        "People who love to eat are always the best people. — Julia Child",
        "Let food be thy medicine and medicine be thy food. — Hippocrates",
        "Tell me what you eat, and I will tell you what you are. — Jean Anthelme Brillat-Savarin",
        "You don’t need a silver fork to eat good food. — Paul Prudhomme",
        "The secret of success in life is to eat what you like. — Mark Twain",
        "First we eat, then we do everything else. — M.F.K. Fisher",
        "Life is uncertain. Eat dessert first. — Ernestine Ulmer",
        "Cooking is like love; it should be entered into with abandon or not at all. — Harriet Van Horne",
        "We all eat, and it would be a sad waste of opportunity to eat badly. — Anna Thomas",
        "Good food is the foundation of genuine happiness. — Auguste Escoffier",
        "There is no sincerer love than the love of food. — George Bernard Shaw",
        "You are what you eat. — Anthelme Brillat-Savarin",
        "To eat is a necessity, but to eat intelligently is an art. — La Rochefoucauld",
        "A recipe has no soul. You, as the cook, must bring soul to the recipe. — Thomas Keller",
        "Food is symbolic of love when words are inadequate. — Alan D. Wolfelt",
        "The belly rules the mind. — Spanish Proverb",
        "All happiness depends on a leisurely breakfast. — John Gunther",
        "Laughter is brightest in the place where the food is. — Irish Proverb",
        "Pull up a chair. Take a taste. Life is so endlessly delicious. — Ruth Reichl",
        "Food is our common ground, a universal experience. — James Beard",
        "My weaknesses have always been food and men—in that order. — Dolly Parton",
        "There is no love sincerer than the love of food. — George Bernard Shaw",
        "If more of us valued food and cheer and song above hoarded gold, it would be a merrier world. — J.R.R. Tolkien",
        "A balanced diet is a cookie in each hand. — Barbara Johnson",
        "People who love to eat are always the best people. — Julia Child",
        "Eat breakfast like a king, lunch like a prince, and dinner like a pauper. — Adelle Davis",
        "One cannot think well if one has not dined well. — Virginia Woolf",
        "Food brings people together on many different levels. — Giada De Laurentiis",
        "The only time to eat diet food is while you're waiting for the steak to cook. — Julia Child",
        "We should look for someone to eat and drink with before looking for something to eat and drink. — Epicurus",
        "Food is an important part of a balanced diet. — Fran Lebowitz",
        "Good painting is like good cooking; it can be tasted, but not explained. — Maurice de Vlaminck",
        "There is no spectacle on earth more appealing than that of a beautiful woman in the act of cooking dinner for someone she loves. — Tom Wolfe",
        "Eat food. Not too much. Mostly plants. — Michael Pollan",
        "First we eat, then we do everything else. — M.F.K. Fisher",
        "Ask not what you can do for your country. Ask what’s for lunch. — Orson Welles",
        "Life is a combination of magic and pasta. — Federico Fellini",
        "I cook with wine, sometimes I even add it to the food. — W.C. Fields",
        "Cooking is at once child’s play and adult joy. — Craig Claiborne",
        "To eat is to appropriate by destruction. — Jean-Paul Sartre",
        "Food is culture, habit, craving and identity. — Jonathan Safran Foer",
        "Food is not just eating energy. It’s an experience. — Guy Fieri",
        "Food is everything we are. — Anthony Bourdain",
        "The discovery of a new dish does more for human happiness than the discovery of a star. — Brillat-Savarin",
        "After a good dinner one can forgive anybody, even one’s own relations. — Oscar Wilde",
        "There is no sincerer love than the love of food. — George Bernard Shaw",
        "I am not a glutton — I am an explorer of food. — Erma Bombeck",
        "Food is our common ground. — James Beard",
        "Give a man food, and he can eat for a day; teach a man how to fish, and he can eat forever. — Chinese Proverb",
        "Food is the most primitive form of comfort. — Sheilah Graham",
        "You don't need a silver fork to eat good food. — Paul Prudhomme",
        "We are better throughout the year for having, in spirit, become a child again at Christmastime. — Laura Ingalls Wilder",
        "Happiness is a small house, a big kitchen, and a garden. — Alfred Hitchcock",
        "The kitchen is the heart of the home. — Anonymous",
        "An empty stomach is not a good political advisor. — Albert Einstein",
        "A party without cake is just a meeting. — Julia Child",
        "Wine is bottled poetry. — Robert Louis Stevenson",
        "Pull up a chair. Take a taste. — Ruth Reichl",
        "Cakes are special. Every birthday, every celebration ends with something sweet. — Buddy Valastro",
        "The fondest memories are made when gathered around the table. — Anonymous",
        "Food is a central activity of mankind and one of the single most significant trademarks of a culture. — Mark Kurlansky",
        "To eat is a necessity, but to eat intelligently is an art. — La Rochefoucauld",
        "There is no love sincerer than the love of food. — G.B. Shaw",
        "A good meal makes a man feel more charitable toward the world. — Arthur Pendenys",
        "In wine there is wisdom, in beer there is freedom, in water there is bacteria. — Benjamin Franklin (attributed)",
        "The only thing I like better than talking about food is eating. — John Walters",
        "If you really want to make a friend, go to someone’s house and eat with him. — Cesar Chavez",
        "Food is the ingredient that binds us together. — Anonymous",
        "The highlight of my childhood was making my brother laugh so hard that food came out of his nose. — Garrison Keillor",
        "We all eat and it would be a sad waste of opportunity to eat badly. — Anna Thomas",
        "People who love to eat are always the best people. — Julia Child",
        "Food should be fun. — Thomas Keller",
        "The way to the heart is through the stomach. — Anonymous",
        "One cannot think well, love well, sleep well, if one has not dined well. — Virginia Woolf",
        "A fit, healthy body—that is the best fashion statement. — Jess C. Scott",
        "Eat to live, don’t live to eat. — Benjamin Franklin",
        "A gourmet who thinks of calories is like a tart who looks at her watch. — James Beard",
        "There is no love sincerer than the love of food. — Shaw",
        "Good bread is the most fundamentally satisfying of all foods. — James Beard",
        "The measurement of love is to love without measure. — Augustine (adapted for food)",
        "If you’re afraid of butter, use cream. — Julia Child",
        "You learn a lot about someone when you share a meal together. — Anthony Bourdain",
        "The only real stumbling block is fear of failure. In cooking you’ve got to have a what-the-hell attitude. — Julia Child",
        "Food is art. — Anonymous",
        "To eat is human; to digest, divine. — Mark Twain",
        "Seize the moment. Remember all those women on the ‘Titanic’ who waved off the dessert cart. — Erma Bombeck",
        "I live on good soup, not on fine words. — Molière",
        "We feast on a lot of food for thought, but we also need food for the body. — Anonymous",
        "Life is too short for self-hatred and celery sticks. — Marilyn Wann",
        "Food is life. — Anonymous",
        "Part of the secret of success in life is to eat what you like. — Mark Twain",
        "The belly has no ears. — Italian Proverb",
        "You have to taste a culture to understand it. — Deborah Cater",
        "Food is the language of care. — Anonymous",
        "Eat well, travel often. — Anonymous",
        "One of the very nicest things about life is the way we must regularly stop whatever it is we are doing and devote our attention to eating. — Luciano Pavarotti",
        "Your diet is a bank account. Good food choices are good investments. — Bethenny Frankel",
        "Food may be essential as fuel for the body, but good food is fuel for the soul. — Malcolm Forbes",
        "The shared meal elevates eating from a mechanical process to a ritual. — Michael Pollan",
        "Cooking is love made visible. — Anonymous",
        "Food is love, food is fun. — Anonymous",
        "Eat good, feel good. — Anonymous",
        "Everything you see I owe to spaghetti. — Sophia Loren",
        "There is nothing more romantic than Italian food. — Elisha Cuthbert",
        "Life is a combination of magic and pasta. — Fellini",
        "Food is joy. — Anonymous"
    )

    fun random(): String = quotes.random()
}


